In [35]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [36]:
data = pd.read_csv('/Users/auliaazmi/Desktop/Bangkit ML/master_table_bersihkan_diy.csv')
data.head(5)

,Sisa Makanan,Kayu/Ranting,Kertas/Karton,Plastik,Logam,Kain,Karet/Kulit,Kaca,Lainnya,postal_code,...,Nama Fasilitas,Jenis,Status,Sampahmasuk (ton/thn),Sampahterkelola (ton/thn),Bahan baku Pakan Ternak,Bahan baku Kompos,Bahan baku Daur Ulang,Bahan baku Up-cycle,Bahan baku Sumber Energi
0,0,1,1,1,1,1,1,1,1,55671,...,pelapak tpa 5,Lapak,A,390.55,390.55,0.0,0.0,390.55,0.0,0.0
1,0,1,1,1,1,1,1,1,1,55664,...,Rubikin,Lapak,A,390.55,390.55,0.0,0.0,390.55,0.0,0.0
2,0,1,1,1,1,1,1,1,1,55652,...,Catur Berkah Rosok,Pengepul,A,390.55,390.55,0.0,0.0,390.55,0.0,0.0
3,0,1,1,1,1,1,1,1,1,55674,...,Sukirman,Lapak,A,390.55,390.55,0.0,0.0,390.55,0.0,0.0
4,0,1,1,1,1,1,1,1,1,55652,...,Patoni,Pengepul,A,390.55,390.55,0.0,0.0,390.55,0.0,0.0

In [37]:
data.columns

Index(['Sisa Makanan', 'Kayu/Ranting', 'Kertas/Karton', 'Plastik', 'Logam',
       'Kain', 'Karet/Kulit', 'Kaca', 'Lainnya', 'postal_code', 'Provinsi',
       'Kabupaten/Kota', 'Kelurahan', 'Kecamatan', 'Fasilitas_ID', 'P',
       'Nama Fasilitas', 'Jenis', 'Status', 'Sampahmasuk (ton/thn)',
       'Sampahterkelola (ton/thn)', 'Bahan baku Pakan Ternak',
       'Bahan baku Kompos', 'Bahan baku Daur Ulang', 'Bahan baku Up-cycle',
       'Bahan baku Sumber Energi'],
      dtype='object')

In [38]:
data['Jenis'].unique()

array(['Lapak', 'Pengepul', 'BSU', 'TPS 3R / UPS', 'BSI',
       'TPA Pemda (Non Regional)', 'TPA Regional', 'TPST (diluar TPA)'],
      dtype=object)

In [39]:
data['Status'].unique()

array(['A'], dtype=object)

In [40]:
data['P'].unique()

array([2, 1])

In [41]:
import pandas as pd

# Sample data with a categorical column
data_ohe = data['Jenis'].unique()

# One-hot encode the 'Category' column
data_encoded = pd.get_dummies(data, columns=['Jenis'], prefix='Jenis')

# Display the resulting DataFrame
data = data_encoded

data

,Sisa Makanan,Kayu/Ranting,Kertas/Karton,Plastik,Logam,Kain,Karet/Kulit,Kaca,Lainnya,postal_code,...,Bahan baku Up-cycle,Bahan baku Sumber Energi,Jenis_BSI,Jenis_BSU,Jenis_Lapak,Jenis_Pengepul,Jenis_TPA Pemda (Non Regional),Jenis_TPA Regional,Jenis_TPS 3R / UPS,Jenis_TPST (diluar TPA)
0,0,1,1,1,1,1,1,1,1,55671,...,0.0,0.0,0,0,1,0,0,0,0,0
1,0,1,1,1,1,1,1,1,1,55664,...,0.0,0.0,0,0,1,0,0,0,0,0
2,0,1,1,1,1,1,1,1,1,55652,...,0.0,0.0,0,0,0,1,0,0,0,0
3,0,1,1,1,1,1,1,1,1,55674,...,0.0,0.0,0,0,1,0,0,0,0,0
4,0,1,1,1,1,1,1,1,1,55652,...,0.0,0.0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5433,1,0,0,0,0,0,0,0,0,55583,...,0.0,0.0,0,0,0,0,0,0,0,1
5434,0,0,0,0,0,0,0,0,0,55583,...,0.0,0.0,0,1,0,0,0,0,0,0
5435,0,0,0,0,0,0,0,0,0,55583,...,0.0,0.0,0,1,0,0,0,0,0,0
5436,0,1,1,1,1,1,1,1,1,55583,...,0.0,0.0,0,1,0,0,0,0,0,0
5437,0,1,1,1,1,1,1,1,1,55583,...,0.0,0.0,0,1,0,0,0,0,0,0

In [42]:
i = 0
for col in data.columns:
    print(f'{i} - {col}')
    i=i+1

0 - Sisa Makanan
1 - Kayu/Ranting
2 - Kertas/Karton
3 - Plastik
4 - Logam
5 - Kain
6 - Karet/Kulit
7 - Kaca
8 - Lainnya
9 - postal_code
10 - Provinsi
11 - Kabupaten/Kota
12 - Kelurahan
13 - Kecamatan
14 - Fasilitas_ID
15 - P
16 - Nama Fasilitas
17 - Status
18 - Sampahmasuk (ton/thn)
19 - Sampahterkelola (ton/thn)
20 - Bahan baku Pakan Ternak
21 - Bahan baku Kompos
22 - Bahan baku Daur Ulang
23 - Bahan baku Up-cycle
24 - Bahan baku Sumber Energi
25 - Jenis_BSI
26 - Jenis_BSU
27 - Jenis_Lapak
28 - Jenis_Pengepul
29 - Jenis_TPA Pemda (Non Regional)
30 - Jenis_TPA Regional
31 - Jenis_TPS 3R / UPS
32 - Jenis_TPST (diluar TPA)

In [43]:
df = data.copy()

In [44]:
cols1 = df.columns[10:14]
cols1

Index(['Provinsi', 'Kabupaten/Kota', 'Kelurahan', 'Kecamatan'], dtype='object')

In [45]:
df = data.drop(columns=cols1)
i = 0
for col in df.columns:
    print(f'{i} - {col}')
    i=i+1

0 - Sisa Makanan
1 - Kayu/Ranting
2 - Kertas/Karton
3 - Plastik
4 - Logam
5 - Kain
6 - Karet/Kulit
7 - Kaca
8 - Lainnya
9 - postal_code
10 - Fasilitas_ID
11 - P
12 - Nama Fasilitas
13 - Status
14 - Sampahmasuk (ton/thn)
15 - Sampahterkelola (ton/thn)
16 - Bahan baku Pakan Ternak
17 - Bahan baku Kompos
18 - Bahan baku Daur Ulang
19 - Bahan baku Up-cycle
20 - Bahan baku Sumber Energi
21 - Jenis_BSI
22 - Jenis_BSU
23 - Jenis_Lapak
24 - Jenis_Pengepul
25 - Jenis_TPA Pemda (Non Regional)
26 - Jenis_TPA Regional
27 - Jenis_TPS 3R / UPS
28 - Jenis_TPST (diluar TPA)

In [46]:
cols2 = [df.columns[12:14]]
cols2

[Index(['Nama Fasilitas', 'Status'], dtype='object')]

In [47]:
df.columns

Index(['Sisa Makanan', 'Kayu/Ranting', 'Kertas/Karton', 'Plastik', 'Logam',
       'Kain', 'Karet/Kulit', 'Kaca', 'Lainnya', 'postal_code', 'Fasilitas_ID',
       'P', 'Nama Fasilitas', 'Status', 'Sampahmasuk (ton/thn)',
       'Sampahterkelola (ton/thn)', 'Bahan baku Pakan Ternak',
       'Bahan baku Kompos', 'Bahan baku Daur Ulang', 'Bahan baku Up-cycle',
       'Bahan baku Sumber Energi', 'Jenis_BSI', 'Jenis_BSU', 'Jenis_Lapak',
       'Jenis_Pengepul', 'Jenis_TPA Pemda (Non Regional)',
       'Jenis_TPA Regional', 'Jenis_TPS 3R / UPS', 'Jenis_TPST (diluar TPA)'],
      dtype='object')

In [48]:
df = df.drop(columns=['Nama Fasilitas', 'Status'])

In [49]:
i = 0
for col in df.columns:
    print(f'{i} - {col}')
    i=i+1

0 - Sisa Makanan
1 - Kayu/Ranting
2 - Kertas/Karton
3 - Plastik
4 - Logam
5 - Kain
6 - Karet/Kulit
7 - Kaca
8 - Lainnya
9 - postal_code
10 - Fasilitas_ID
11 - P
12 - Sampahmasuk (ton/thn)
13 - Sampahterkelola (ton/thn)
14 - Bahan baku Pakan Ternak
15 - Bahan baku Kompos
16 - Bahan baku Daur Ulang
17 - Bahan baku Up-cycle
18 - Bahan baku Sumber Energi
19 - Jenis_BSI
20 - Jenis_BSU
21 - Jenis_Lapak
22 - Jenis_Pengepul
23 - Jenis_TPA Pemda (Non Regional)
24 - Jenis_TPA Regional
25 - Jenis_TPS 3R / UPS
26 - Jenis_TPST (diluar TPA)

In [50]:
df

,Sisa Makanan,Kayu/Ranting,Kertas/Karton,Plastik,Logam,Kain,Karet/Kulit,Kaca,Lainnya,postal_code,...,Bahan baku Up-cycle,Bahan baku Sumber Energi,Jenis_BSI,Jenis_BSU,Jenis_Lapak,Jenis_Pengepul,Jenis_TPA Pemda (Non Regional),Jenis_TPA Regional,Jenis_TPS 3R / UPS,Jenis_TPST (diluar TPA)
0,0,1,1,1,1,1,1,1,1,55671,...,0.0,0.0,0,0,1,0,0,0,0,0
1,0,1,1,1,1,1,1,1,1,55664,...,0.0,0.0,0,0,1,0,0,0,0,0
2,0,1,1,1,1,1,1,1,1,55652,...,0.0,0.0,0,0,0,1,0,0,0,0
3,0,1,1,1,1,1,1,1,1,55674,...,0.0,0.0,0,0,1,0,0,0,0,0
4,0,1,1,1,1,1,1,1,1,55652,...,0.0,0.0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5433,1,0,0,0,0,0,0,0,0,55583,...,0.0,0.0,0,0,0,0,0,0,0,1
5434,0,0,0,0,0,0,0,0,0,55583,...,0.0,0.0,0,1,0,0,0,0,0,0
5435,0,0,0,0,0,0,0,0,0,55583,...,0.0,0.0,0,1,0,0,0,0,0,0
5436,0,1,1,1,1,1,1,1,1,55583,...,0.0,0.0,0,1,0,0,0,0,0,0
5437,0,1,1,1,1,1,1,1,1,55583,...,0.0,0.0,0,1,0,0,0,0,0,0

In [51]:
df.columns

Index(['Sisa Makanan', 'Kayu/Ranting', 'Kertas/Karton', 'Plastik', 'Logam',
       'Kain', 'Karet/Kulit', 'Kaca', 'Lainnya', 'postal_code', 'Fasilitas_ID',
       'P', 'Sampahmasuk (ton/thn)', 'Sampahterkelola (ton/thn)',
       'Bahan baku Pakan Ternak', 'Bahan baku Kompos', 'Bahan baku Daur Ulang',
       'Bahan baku Up-cycle', 'Bahan baku Sumber Energi', 'Jenis_BSI',
       'Jenis_BSU', 'Jenis_Lapak', 'Jenis_Pengepul',
       'Jenis_TPA Pemda (Non Regional)', 'Jenis_TPA Regional',
       'Jenis_TPS 3R / UPS', 'Jenis_TPST (diluar TPA)'],
      dtype='object')

In [52]:
import pandas as pd

column_mapping = {'postal_code':'user_id', 'Fasilitas_ID': 'item_id'}

# Create a new dataset with selected columns and renamed
dfs = df[list(column_mapping.keys())].copy()
dfs.rename(columns=column_mapping, inplace=True)

dfs

      user_id  item_id
0       55671        1
1       55664        2
2       55652        3
3       55674        4
4       55652        5
...       ...      ...
5433    55583      500
5434    55583      501
5435    55583      501
5436    55583      488
5437    55583      488

[5438 rows x 2 columns]

In [53]:
df_duplicated = pd.concat([dfs]*2, ignore_index=True)

In [54]:
# df_duplicated.to_csv('masterdf.csv', index=False)

In [55]:
## Content-based Filtering

In [56]:
# # Extract numerical features
# numerical_features = df[df.columns].values

# # Compute cosine similarity between items based on numerical features
# cosine_sim = cosine_similarity(numerical_features, numerical_features)

# # Function to get content-based recommendations for a given item
# def content_based_recommendations(postal_code, cosine_sim=cosine_sim, df=df):
#     # Get the index of the item
#     idx = df[df['postal_code'] == postal_code].index[0]

#     # Get the pairwise similarity scores
#     sim_scores = list(enumerate(cosine_sim[idx]))

#     # Sort the items based on similarity scores
#     sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

#     # Get the top N most similar items
#     top_n = 5
#     sim_scores = sim_scores[1:top_n + 1]

#     # Get the item indices
#     item_indices = [i[0] for i in sim_scores]

#     # Return the top N similar items
#     return df['postal_code'].iloc[item_indices].tolist()

In [57]:
# # Example: Get content-based recommendations for item_id 101
# postal_code = 55671
# recommendations = content_based_recommendations(postal_code)
# print(f"Content-based recommendations for item {postal_code}: {recommendations}")

In [58]:
# df.to_csv('masterdfdiyv1.csv', index=False)

In [59]:
## Collaborative Filtering

In [60]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split

# Select input columns
input_cols = df.columns[:9]  # Exclude 'Fasilitas_ID' from input

# Map postal codes to unique indices
postal_codes = df['postal_code'].unique()
postal_code_to_index = {code: i for i, code in enumerate(postal_codes)}
df['postal_code_index'] = df['postal_code'].map(postal_code_to_index)

# Split the data into training and validation sets
train_data, val_data = train_test_split(df, test_size=0.2, random_state=42)

# Number of users and items
num_users = len(postal_codes)
num_items = len(df['Fasilitas_ID'].unique())

# Build a collaborative filtering model using matrix factorization with TensorFlow
embedding_dim = 10

# Input features
user_input = tf.keras.layers.Input(shape=(1,), name='postal_code')
other_inputs = [tf.keras.layers.Input(shape=(1,), name=col) for col in input_cols]

# Embedding layers for user and item
user_embedding = tf.keras.layers.Embedding(input_dim=num_users, output_dim=embedding_dim)(user_input)
other_embedding = [tf.keras.layers.Embedding(input_dim=unique_count, output_dim=embedding_dim)(input_) for unique_count, input_ in zip(df[input_cols].nunique(), other_inputs)]

# Flatten the embeddings
user_embedding_flat = tf.keras.layers.Flatten()(user_embedding)
other_embedding_flat = [tf.keras.layers.Flatten()(embedding) for embedding in other_embedding]

# Concatenate the flattened embeddings with other input features
concatenated = tf.keras.layers.Concatenate()([user_embedding_flat] + other_embedding_flat)

# Dense layers for prediction
dense1 = tf.keras.layers.Dense(50, activation='relu')(concatenated)
output = tf.keras.layers.Dense(num_items, activation='softmax')(dense1)  # Softmax for recommendation

model = tf.keras.Model(inputs=[user_input] + other_inputs, outputs=output)
model.compile(optimizer='adam', loss='categorical_crossentropy')  # Use categorical crossentropy for recommendation

# Prepare one-hot encoded labels for training
train_labels = tf.keras.utils.to_categorical(train_data['Fasilitas_ID'] - df['Fasilitas_ID'].min(), num_classes=num_items)
val_labels = tf.keras.utils.to_categorical(val_data['Fasilitas_ID'] - df['Fasilitas_ID'].min(), num_classes=num_items)

# Train the model with a validation split
model.fit([train_data['postal_code_index']] + [train_data[col] for col in input_cols], train_labels,
          epochs=10, batch_size=1, verbose=1,
          validation_data=([val_data['postal_code_index']] + [val_data[col] for col in input_cols], val_labels))

# Make predictions for the entire dataset
predictions = model.predict([df['postal_code_index']] + [df[col] for col in input_cols])

# Select the top-k recommended items for each user
top_k = 5  # Choose the number of top recommendations
recommended_ids = np.argsort(predictions, axis=1)[:, -top_k:]

Epoch 1/10
4350/4350 [==============================] - 5s 1ms/step - loss: 3.1758 - val_loss: 2.7518
Epoch 2/10
4350/4350 [==============================] - 4s 979us/step - loss: 2.7279 - val_loss: 2.6399
Epoch 3/10
4350/4350 [==============================] - 4s 1ms/step - loss: 2.6081 - val_loss: 2.5999
Epoch 4/10
4350/4350 [==============================] - 4s 979us/step - loss: 2.5358 - val_loss: 2.5730
Epoch 5/10
4350/4350 [==============================] - 4s 961us/step - loss: 2.4914 - val_loss: 2.5760
Epoch 6/10
4350/4350 [==============================] - 4s 950us/step - loss: 2.4618 - val_loss: 2.5836
Epoch 7/10
4350/4350 [==============================] - 4s 931us/step - loss: 2.4388 - val_loss: 2.5848
Epoch 8/10
4350/4350 [==============================] - 4s 1ms/step - loss: 2.4173 - val_loss: 2.6030
Epoch 9/10
4350/4350 [==============================] - 5s 1ms/step - loss: 2.4006 - val_loss: 2.6003
Epoch 10/10
4350/4350 [==============================] - 6s 1ms/step - loss: 2.3825 - val_loss: 2.6197
170/170 [==============================] - 0s 662us/step

In [27]:
# # Display the recommended IDs for each user
# for i, rec_ids in enumerate(recommended_ids):
#     print(f"User {postal_codes[i]} - Recommended Fasilitas_ID: {df['Fasilitas_ID'].iloc[rec_ids].tolist()}")

In [61]:
model.save('recommendation_model.h5')

# To load the model later
recommendation_model = tf.keras.models.load_model('recommendation_model.h5')

In [62]:
converter = tf.lite.TFLiteConverter.from_keras_model(recommendation_model)
tflite_model = converter.convert()

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/
WARNING:absl:Function `_wrapped_model` contains input name(s) Sisa Makanan, Kayu/Ranting, Kertas/Karton, Plastik, Logam, Kain, Karet/Kulit, Kaca, Lainnya with unsupported characters which will be renamed to placeholder, kayu_ranting, kertas_karton, plastik, logam, kain, karet_kulit, kaca, lainnya in the SavedModel.

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/
WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/

WARNING:tensorflow:`Sisa Makanan` is not a valid node name. Accepted names conform to Regex /re.compile('^[A-Za-z0-9.][A-Za-z0-9_.\\\\/>-]*$')/
2023-12-20 19:06:09.852163: I tensorflow/core/grappler/devices.cc:75] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2023-12-20 19:06:09.853343: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2023-12-20 19:06:10.091938: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2023-12-20 19:06:10.091957: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.

In [64]:
prediksi = model.predict([np.array([4]), np.array([0]), np.array([1]), np.array([1]), np.array([1]),
               np.array([1]), np.array([1]), np.array([1]), np.array([1]), np.array([1])])

1/1 [==============================] - 0s 27ms/step

In [67]:
prediksi

array([[9.51546186e-04, 1.16134834e-05, 1.86109648e-03, 6.84092447e-05,
        4.04650433e-04, 4.59656614e-04, 3.94496229e-03, 3.34766053e-04,
        3.01032669e-05, 5.30480320e-05, 9.36805445e-04, 1.14162406e-03,
        1.51429531e-05, 3.64686479e-04, 3.88720119e-03, 5.95008241e-05,
        3.92414117e-03, 2.26471570e-08, 3.25976813e-04, 4.10749461e-04,
        3.06187570e-03, 1.01921824e-03, 2.38869511e-08, 1.08825800e-04,
        6.87993132e-04, 5.64604416e-04, 3.17947753e-03, 1.96546689e-03,
        2.46685534e-03, 5.94769558e-03, 2.06998922e-03, 1.73683127e-03,
        1.93750090e-03, 1.90732162e-03, 2.07818113e-03, 3.06274206e-03,
        2.83861416e-03, 1.53137371e-03, 1.91382449e-02, 2.09659128e-03,
        5.11099305e-03, 7.60063762e-03, 5.25868684e-03, 1.81582954e-03,
        6.84393756e-03, 2.04759580e-03, 3.60363349e-03, 2.36152881e-03,
        2.91504664e-03, 7.08988402e-04, 1.71531073e-03, 2.50214734e-03,
        2.74997787e-03, 1.50629680e-03, 2.47612991e-03, 2.40587234e-03,
        1.66285329e-03, 1.90778787e-03, 1.14084885e-03, 1.56420423e-03,
        2.71251495e-03, 3.69140785e-03, 3.97307845e-03, 2.24260613e-03,
        1.04213518e-03, 1.86598289e-03, 1.76229291e-02, 1.83547870e-03,
        2.03742972e-03, 1.70296023e-03, 3.69239971e-03, 2.01908592e-03,
        2.06795745e-02, 6.12942316e-03, 2.71577062e-03, 6.53903605e-03,
        1.55528903e-03, 4.92024375e-03, 1.18242262e-03, 3.66452150e-03,
        2.38775765e-03, 1.81945937e-03, 4.63698059e-03, 2.28218688e-03,
        4.46417741e-03, 4.70483303e-03, 2.19974737e-03, 1.14927453e-03,
        2.39727033e-05, 3.31203546e-03, 1.37626639e-05, 3.66536970e-03,
        3.25343572e-05, 7.45357829e-04, 2.33356119e-03, 3.47691202e-05,
        1.22423487e-04, 2.65953317e-03, 2.47563352e-04, 3.69535905e-04,
        3.09444312e-03, 5.75575104e-05, 2.28460063e-03, 1.27147039e-04,
        3.46270623e-03, 3.90732057e-05, 2.55242013e-03, 8.42139299e-04,
        4.03337600e-03, 1.87199985e-04, 3.70611087e-05, 4.37585823e-03,
        1.88346487e-04, 1.75230653e-05, 1.47144869e-03, 6.57714671e-04,
        5.06424985e-05, 3.49136698e-03, 9.69559362e-04, 7.68398677e-05,
        3.76114366e-03, 4.38602612e-04, 1.09747398e-05, 4.15837712e-05,
        4.26075980e-03, 2.80921510e-03, 5.37685258e-03, 1.18797194e-04,
        3.07486276e-04, 7.13452930e-04, 8.87949063e-05, 3.50665214e-05,
        1.25228587e-04, 2.67551804e-04, 4.53697576e-05, 1.53872475e-03,
        2.26472737e-03, 3.68718640e-04, 3.03719396e-04, 1.88799066e-04,
        1.88973339e-04, 9.84108556e-05, 2.86127784e-06, 1.13508038e-04,
        1.68502083e-04, 4.58481873e-06, 4.68128928e-05, 1.75339403e-03,
        1.54618383e-03, 3.16559477e-03, 1.43491232e-03, 1.06188483e-04,
        2.31621508e-03, 5.26216114e-04, 4.59096744e-04, 9.13815980e-04,
        1.38047224e-04, 1.29406253e-04, 1.09427543e-04, 8.41391098e-04,
        2.23428938e-08, 6.43598760e-05, 3.42544197e-04, 2.19226166e-08,
        5.70065225e-04, 2.24439427e-04, 5.41521236e-04, 3.05777794e-04,
        2.78506032e-03, 1.84629799e-03, 5.10732760e-04, 1.12545572e-03,
        4.22302446e-06, 2.36904190e-04, 5.73756581e-04, 1.06637402e-04,
        2.02965084e-03, 1.44181752e-06, 7.14968166e-07, 1.42687315e-03,
        1.90531649e-03, 3.40023753e-03, 2.58376938e-03, 3.76983848e-03,
        8.43371708e-07, 3.23946727e-03, 1.69206283e-03, 3.09812766e-03,
        2.18304154e-03, 1.40555051e-06, 8.57252758e-07, 2.16313917e-03,
        1.55746646e-03, 7.09144888e-06, 1.73413975e-03, 2.41779326e-03,
        3.13515542e-03, 2.98875314e-03, 3.54913226e-03, 6.53158111e-07,
        1.91164482e-03, 2.86990148e-03, 1.10110943e-03, 1.29522535e-03,
        3.04790377e-03, 2.64370395e-03, 2.21550581e-03, 3.14106769e-03,
        1.59828668e-03, 1.63671630e-03, 7.94232823e-04, 2.57705478e-03,
        2.08955998e-06, 1.12429331e-03, 1.76487640e-06, 2.53258203e-03,
        3.03148431e-06, 3.84523952e-03, 2.21355073e-03, 1.77667380e-06,
        2.67061614e-03, 1.36345398e-06, 2.86467071e-03, 2.77260109e-03,
        1.08036445e-03, 2.44564144e-03, 3.12878541e-03, 2.80276337e-03,
        1.25208874e-06, 1.63554307e-03, 8.03876446e-07, 3.17614921e-03,
        1.06268236e-03, 2.22206139e-03, 2.37734366e-06, 1.24941196e-03,
        2.43407930e-03, 1.87437377e-06, 2.97968791e-06, 1.26063890e-06,
        1.37815312e-06, 1.48926198e-03, 1.97942904e-03, 2.99471407e-03,
        1.15149922e-03, 2.70310813e-03, 2.49461760e-03, 4.06720489e-03,
        1.39663788e-03, 5.96659788e-07, 1.20236291e-06, 2.23181397e-03,
        2.99902610e-03, 1.42280897e-03, 2.86067626e-03, 2.38138787e-03,
        3.39924777e-03, 2.64787395e-03, 2.50424771e-03, 3.26025044e-03,
        1.96497072e-03, 6.77773776e-03, 1.77756692e-06, 3.24599771e-03,
        3.84637387e-03, 3.49036139e-03, 3.38242925e-03, 2.84239161e-03,
        4.17736970e-04, 1.54893298e-03, 2.43970635e-03, 2.89635318e-06,
        5.04781120e-03, 4.79864981e-03, 1.38932944e-03, 3.46281775e-03,
        2.06303643e-03, 1.88215740e-03, 1.96922920e-03, 1.92394271e-03,
        3.11712828e-03, 2.03011651e-03, 1.28693250e-03, 1.69740769e-03,
        2.68737599e-03, 2.54625455e-03, 1.61112109e-06, 2.63139000e-03,
        2.32629292e-03, 2.26753368e-03, 2.70561548e-03, 1.56748132e-03,
        4.05693846e-03, 3.91025888e-03, 1.81799370e-03, 2.20013130e-03,
        1.11624715e-03, 2.00802321e-03, 2.71509844e-03, 2.34487304e-03,
        3.22903879e-03, 2.90241023e-03, 4.19903826e-03, 2.51518795e-03,
        6.69822953e-07, 2.45373580e-03, 2.68327515e-03, 1.85707852e-03,
        4.04480565e-03, 2.33299262e-03, 1.28754904e-03, 4.11396008e-03,
        1.92784239e-03, 2.31094987e-06, 1.52212474e-03, 1.33643982e-06,
        3.86575097e-03, 2.02233833e-03, 2.30108062e-03, 1.81509636e-03,
        1.45653894e-06, 2.98914849e-03, 3.21686245e-03, 1.44273136e-03,
        1.31089462e-03, 2.32296251e-03, 1.53815063e-06, 3.60769383e-03,
        2.21682736e-03, 1.94648078e-06, 9.94117727e-07, 1.52958592e-06,
        1.96853024e-03, 5.66837750e-03, 3.13973799e-03, 1.15545674e-06,
        1.62670831e-03, 3.57716391e-03, 1.07117323e-03, 2.33997358e-03,
        3.10035306e-03, 1.83367194e-03, 1.02592213e-03, 2.91566225e-03,
        2.17153295e-03, 2.32554437e-03, 5.70182223e-04, 3.62511212e-03,
        2.30695726e-03, 3.31311370e-03, 2.63589690e-03, 1.14153681e-06,
        1.97654497e-03, 1.94302923e-03, 2.80022598e-03, 1.75850769e-03,
        3.67393056e-07, 1.40770896e-06, 1.43160321e-06, 4.16334274e-07,
        1.27931044e-03, 2.32417551e-06, 3.04866349e-03, 1.76828587e-03,
        5.95366536e-03, 2.53936951e-03, 9.29324017e-07, 1.04391424e-03,
        2.15813913e-03, 1.74061605e-03, 1.64571406e-06, 1.50677988e-06,
        2.76307086e-03, 2.23320932e-03, 3.65639362e-03, 2.50622048e-03,
        2.49729828e-06, 3.40429251e-03, 3.36403353e-03, 9.67551547e-04,
        3.91160743e-03, 4.13466757e-03, 1.24263408e-06, 4.49402304e-03,
        2.28993013e-03, 3.75849381e-03, 1.84910861e-03, 2.10732035e-03,
        2.69106822e-03, 4.99721896e-03, 1.31671049e-03, 4.12645424e-03,
        4.20620153e-03, 6.17279341e-07, 1.98218320e-03, 1.26430621e-06,
        2.68631452e-03, 2.84381933e-03, 8.10299721e-03, 3.08096176e-03,
        2.75260891e-06, 2.61412770e-03, 1.29284251e-06, 2.65170890e-03,
        2.75621819e-03, 5.84332497e-07, 1.48387778e-06, 3.46949650e-03,
        2.22968729e-03, 4.58987663e-03, 3.28076934e-03, 1.84746762e-03,
        3.68099334e-03, 1.75624515e-03, 1.67360879e-03, 8.74094723e-04,
        2.37291079e-06, 1.00034000e-02, 2.75367452e-03, 8.92299965e-07,
        2.04238412e-03, 1.99951418e-03, 1.48739991e-06, 1.91180618e-03,
        1.95609027e-06, 6.35014195e-03, 1.33090577e-06, 4.96737007e-03,
        2.73576123e-03, 2.93477811e-03, 7.32935348e-07, 2.06252537e-03,
        9.62932063e-07, 3.68332700e-03, 9.61672748e-04, 5.21964254e-03,
        3.35282320e-03, 2.53827381e-03, 3.01366090e-03, 1.28328055e-03,
        5.70473162e-07, 4.28366263e-07, 3.12459352e-03, 7.06132653e-07,
        2.85463920e-03, 2.16709100e-06, 2.74391193e-03, 1.22268696e-03,
        1.54516511e-06, 1.15667097e-03, 1.19783408e-06, 1.68827688e-03,
        3.31894355e-03, 1.77441996e-06, 2.69615464e-03, 1.36384345e-03,
        2.33332696e-03, 1.22466929e-06, 2.86850869e-03, 2.54888716e-03,
        3.89664341e-03, 4.53836517e-03, 1.72323338e-03, 1.13734056e-03,
        1.67136182e-04, 1.63371279e-03, 2.07665819e-03, 2.93008816e-05,
        2.57457414e-05, 1.58422165e-06, 2.36408795e-08, 1.07173355e-06,
        1.79549045e-06, 2.96757594e-06, 1.60876289e-06, 1.65425854e-06,
        2.25434678e-06, 1.35708046e-06, 1.08848121e-06, 2.20521586e-03,
        2.89772375e-04, 1.11440709e-03, 9.89782166e-07, 3.84450232e-06,
        2.31379005e-08, 1.62124297e-06, 4.67441714e-05, 2.77395663e-03,
        4.94113692e-07, 6.01873174e-03, 4.62089153e-03, 7.19370460e-03,
        4.69833007e-03, 4.30827960e-03, 6.42958656e-03, 6.80920854e-03,
        5.52689936e-03, 5.34917274e-03, 5.03448304e-03, 5.59975923e-08,
        1.17885747e-06, 4.35488706e-04, 1.97381433e-03, 1.35666982e-03,
        1.52241206e-03, 1.03986159e-03, 1.48906163e-03]], dtype=float32)

In [65]:
top_k = 5  # Choose the number of top recommendations
recommended_ids = np.argsort(prediksi, axis=1)[:, -top_k:]

In [66]:
recommended_ids

array([[398, 417,  66,  38,  72]])